### ISSUE TITLE
Linear Shifted FOV

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MDF#10]
From @MandyA:
1.       In terms of sequence description: from my experience just sinusoidal signals is not enough to describe sequences. E.G. a linear shifted FOV (as done by Jürgen) cannot be described appropriately. However, I think it is quite tricky to cover all possible sequences.

**Comment by tknopp** [comment]
Hm I am not sure I can follow. So drive-field is currently restricted to be sinusoidal. But you requested Linear shifted FF sequences. I think this should be doable by using numPatches and specifying the FOV centers.
So FOV center would be kind of a sampled version of the linear ramp.
We could introduce a new parameter that specifies, whether the FF is linear or static (constant) this would cover at least this use case.

In general this is the trickiest part of the specification: But we could also say: Not supported at this time point but we will rethink this once we can play around with dynamic FF sequences.

**Comment by hofmannmartin** [comment]
One Idea to support such cases could be to add two additional fields. One which stores in which direction the fov moves during the drive field cycle and one, which stores the durations of how long the fov moves into a particular direction.

That way it should be also possible to approximate more complex fov movements.

**Comment by ckaethner** [comment]
@tknopp Should we maybe differantiate between continuous and static movement, rather than linear and static? The term "continuous" covers more.

@hofmannmartin Good Idea! I'm just not quite sure, if this would fully describe the FF possibilities. For example, when I think this kind of enlongated FFP trajectory, which could also be realized by use of an linear FF shift, the movement speed is an important factor as well. But maybe, I missunderstood part of your idea.

**Comment by hofmannmartin** [comment]
@ckaethner maybe not all possibilities are covered, but at least such cases where some sort of slow movement of the fov is superimposed with the fast FFP movement. In the end even more complicated cases can be approximated by concatenation of linear shifts.

In the end the FFP trajectory depends on the drive fields and the fov shift. But the fov shift is slow and does not contribute to the excitation of particles. Furthermore, the fov shift might also be realized mechanically. That is why this kind of shift should in any case be separated from the drive fields.

So I would realize FFP shifts via the additional and optional fields
* fieldOfViewVelocities JxTx3
* fieldOfViewMovementTimes JxT

**Comment by tknopp** [comment]
I think this is an important issue which needs a satisfying solution.
Since it is not 100% clear what will be needed we should first play around with different possibilities and see if this fits. Currently we are not able to capture such data such that I do not see a rush (in HH). But @ckaethner can go ahead here with a proposal. We should also try getting data from the US. My plan is to send a request to them once HL and HH and BS are fine with the specification.

**Comment by hofmannmartin** [comment]
I think this issue will resolve itself together with #53.

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
