### ISSUE TITLE
Inconsistent plural `/calibration/offsetFields`

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MDF#106]
The specs define the path for the calibration offsets to be `/calibration/offsetFields` with a plural `s` but MPIFiles uses the singular in https://github.com/MagneticParticleImaging/MPIFiles.jl/blob/79a7113d7c26d4e9aff493f8c1643a1617a0d204/src/MDF.jl#L428C1-L428C74. Since I copied the MDF specs for the in-memory MDF, I also copied the plural version which is now not exported. Should this be changed in the specs or MPIFiles (maybe with an alias)?

**Comment by tknopp** [comment]
the spec is correct. It's symmetric with positions. This should be fixed in MPIFiles. I don't think we have ever written this field so far. So this can simply be changed with an appropriate version bump of MPIFiles.
