### ISSUE TITLE
Simulated MDF Data

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MDF#11]
From @MandyA:

6.       It would be great if not just experimental data but simulation data as well would be stored in MDF. In several cases our collaborators like to start with modeled (ideal) data. Currently, I do not see an issue with that. I was just wondering if we should give a guideline in the scanner-group how to differentiate these two cases.

**Comment by tknopp** [comment]
Yes. Simulated data would be certainly nice. I am fine with an additional flag indicating that this is simulated data. Additionally one has the opportunity to naming the Scanner appropriately: "IMTSimulationMachine"

**Comment by tknopp** [comment]
updated specification. Please review @MandyA

**Comment by MandyA** [comment]
Thanks for adding.
