### ISSUE TITLE
SI Units should be used

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#14]
André Behrends (IMT Lübeck) requests that all units should be changed to SI units.

I have to agree. It certainly is no good practice to use non SI units.

**Comment by ckaethner** [comment]
This is definitely a good point and I would agree with him as well. SI units should be a must, especially when we talk about a standardized data format.

**Comment by tknopp** [comment]
I have updated the specification to remove all "milli". Interestingly it seems that I don't have to change the  data (nor our conversion routine) since we never stored mm or ms.

Also added a comment about the MPI convention to report the field strength in T/\mu_0

**Comment by hofmannmartin** [comment]
Was machen wir mit den Tracerparametern (volume und concentration haben noch nicht reine SI Einheiten)?

**Comment by tknopp** [comment]
Ups ;-)
Ist geändert.

**Comment by hofmannmartin** [comment]
Ich denke damit kann das Issue geschlossen werden.
