### ISSUE TITLE
Will tracer allways be iron?

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#15]
At the moment the tracer concentration is provided in mol(Fe)/L. Is the tracer always going to be fully described by its iron content or are other tracer materials possible?

**Comment by gBringout** [comment]
It will depend on the applications.

I suppose that the tracer concentration is given as the iron quantity to
easily make the link with its bio-compatibility.

For applications more tolerant on this aspect, other elements may be used.

--
Gaël Bringout

2016-01-18 8:52 GMT+01:00 Martin Hofmann <notifications@github.com>:

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
