### ISSUE TITLE
sanity checks

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#17]
We just got a great remark from J. Rahmer. He proposed to introduce sanity checks, since some of the parameters are redundant.

I think this is a great Idea and we should implement this in the basic languages to make the usage of our file format simpler.

**Comment by tknopp** [comment]
In principle this is of course a good idea. But I wonder how many redundant parameters we have. drive field strength and fov is clear. This was done on purpose. A second redundancy might be in the sampling rate and the frequency index.

**Comment by gBringout** [comment]
Regarding this example (drive field strength and fov), for an "ideal
scanner" it is simple. For a real one not that easy. So for the sanity
check, a given model should always be provided.

Everythings link to the signal encoding is good I think (sampling rate,
frequency index, but also why not the repetition time, frequency
resolution, time resolution, number of ideal muster). Everythings evolving
around the averaging, the numbers of points saved would be usefull.

As some people understand better the sampling rate and other the time
resolution, this could also helps some person to read und understand the
datas.



--
Gaël Bringout

2016-01-29 19:54 GMT+01:00 Tobias Knopp <notifications@github.com>:

**Comment by hofmannmartin** [comment]
> Regarding this example (drive field strength and fov), for an "ideal scanner" it is simple. For a real one not that easy. So for the sanity check, a given model should always be provided.

If we provide information such as drive field and gradient I think we should view it as some kind of order zero approximation to the real fields. In a second step one might think of providing information, how the real field deviate from the ideal ones as these can not be described by a few parameters anyway.

> As some people understand better the sampling rate and other the time resolution, this could also helps some person to read und understand the datas.

An argument supporting consistency checks.

**Comment by hofmannmartin** [comment]
I just made an overview of groups of parameters depending on eachother.

1. 
    * `/acquisition/gradient`
    * `/acquisition/drivefield/strength`
    * `/acquisition/drivefield/fieldOfView`

2. 
    * `/aquisition/receiver/bandwidth`
    * `/aquisition/receiver/numSamplingPoints`
    * `/aquisition/receiver/frequencies`
    * `/acquisition/drivefield/period`

3. 
    * `/acquisition/drivefield/period`
    * `/acquisition/drivefield/averages`
    * `/acquisition/drivefield/repetitionTime`

4. 
    * `/calibration/size/`
    * `/calibration/positions/`

5. 
    * `/reconstruction/size/`
    * `/reconstruction/positions/`

6. 
    * `/calibration/deltaSampleSize/`
    * `/tracer/volume`

Is anything missing?

**Comment by tknopp** [comment]
more than I initially thought. I don't see any further ones

**Comment by hofmannmartin** [comment]
Sanity checks were removed as of version 2.0.0.
