### ISSUE TITLE
Validity check

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#18]
If we provide sanity checks it would be nice to have a validity check in the first place. Such that we offer a function to check, weather all non optional fields are set and that all fields set have the correct type and dimension.

I think this would be a great help for people, who want to start using MDF at their facility.

**Comment by tknopp** [comment]
Yes, I think this all fits together under a validity check. Not sure if we need to differentiate between type mismatches and value inconsistencies

I am not sure though where to put that. In principle this should be part of a "loader" routine that provides high level access to MDF files. But this currently is not part of the MDF project which in contrast provide low level routines where one can directly see how to access the data.

Currently it seems that a validity check is especially important for people generating MDF files. Thus we should probably start implementing it within MPILib but make it easy to split out into the public MDF repo in case someone else wants to use it.

**Comment by hofmannmartin** [comment]
I agree that all fits under validity check, but I would nonetheless have the possibility to independently check types in a low-level routine, since this would be the first source of mistake implementing MDF.

As for a high-level routine all of this should be included in one function.

**Comment by gBringout** [comment]
I will need more time to look at #17, but as both are linked I will put my
first though here.

I think that considering a single sided scanner is a good way to avoid
quite a lot of misunderstanding between MPI and 3D Lissajous based systems.

For example, the gradient strength of a single sided scanner can not be
described by a single value, and then the whole Validity/Sanity check start
to be tricky. In the coming time, we want to change the data format of the
one online coming from IMT's single sided scanner to the MDF format, so it
would be better if we could also take into account the single sided scanner
into all the Validity/Sanity checks.

Going further, the scanners using a linear shifts could be also hard to
integrate. I just need more time to check that.

--
Gaël Bringout

2016-01-31 21:04 GMT+01:00 Martin Hofmann <notifications@github.com>:

**Comment by hofmannmartin** [comment]
As we just released the v1.0 of the specifications, we should at first design the checks for this version.

In a second step in another issue we should start making changes, such that the single sided scanner is covered. If possible we should try to keep the updated specifications backwards compatible.

**Comment by tknopp** [comment]
Lets keep that separate. The one is the specification, the other are sanity checks that could be part of a software that is also provided. But @gBringout: Do you see any issues describing single-sided measurement data? Yes I see that gradient is not constant and thus the parameter is not generic enough but the measurement data is still describable. The alternative is to put all field profiles into the files and this is usually not possible because they are not always measured.

**Comment by hofmannmartin** [comment]
accidentally closed

**Comment by hofmannmartin** [comment]
I Think the last thing we need, which is not related to check if redundant data is coherent is a check for the dimensionality of the fields. At the moment we only check, if a dataset has the correct number of dimensions.

Just yesterday I came across a problem, where the dimensions in one dataset were swaped, which is currently not detected by our sanitycheck.

**Comment by hofmannmartin** [comment]
I think validity should not check if redundant data is coherent. So we can close this one. Basic checks have been introduced in version 1.0.1.
