### ISSUE TITLE
2 level system of optional/non-optional parameters

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#20]
We should think of a 2 level system of optional/non-optional parameters, such that whenever a systemfunction is stored the necessary elements in the calibration group are non-optional. Likewise for a measurement at least either dataFd or dataTD should be provided.

**Comment by profix898** [comment]
Not sure I understand how you would enforce a certain combination of parameters in HDF5. Also, a 2 level approach sounds too coarse grained to me.
Third, a "correct" combination of parameters is subject to the actual experiment IMO. For restricting or enforced grouping of parameters, we must be very careful not to draft ourselves into a corner, which limits the universal use of MDF for future application scenarios or new scanner designs.

One option would be to provide "access profiles" to MDF, which in my mind is equivalent to a class description in OO code or a "view" in database design. A profile for a "2D FFP Lissajous ..." experiment would then provide access to just the right set of parameters, while for other profiles a different set is accessible. But in general this should be a "support construct" in the MDF access layer of the software, than an intrinsic property of the MDF format itself.


@hofmannmartin: Do you plan on using MDF as your primary storage format (to run your reconstruction against it directly)? I'm considering MDF an exchange data format for MPI data, but not the internal representation of MPI data in my software. I guess the answer to that question, drastically changes the view on MDF and its feature set. For example, your issue #28.

**Comment by hofmannmartin** [comment]
@profix898 The idea is not to provide some kind of software solution, but merely to be more fine grained within the specifications. Take for example the `calibration` group. There everything is optional, which in principle would mean, that someone might only supply `dataFD`. But without the `positions` one would not be able to reshape reconstructed data into an image. So at the very least a `MDF` which contains a `calibration` should enable the the user to interpret reconstructed data.

But I agree that we have to be careful to avoid restricting ourselves in the future. 

A the moment I think I would use `MDF` as exchange format. But for the future I also plan on using it to store reconstruction results.

**Comment by hofmannmartin** [comment]
We did add a more fine grained system for optional parameters and groups in version 2.0.0.
