### ISSUE TITLE
Update Example files

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#25]
@tknopp we should update the `MDF` files on https://www.tuhh.de/ibi/research/mpi-data-format.html to be conform with our v1.0 specifications. Did you create the Files with a script, which you can rerun?

**Comment by tknopp** [comment]
its on `mpiresults` but needs to be updated due to the API changes

**Comment by hofmannmartin** [comment]
I just replaced the old files by newly generated ones. These satisfy the v1.0 MDF specifications.
