### ISSUE TITLE
channel x frequency dimension in /measurement/dataFD and /measurement/dataTD

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#28]
Maybe I am mistaken, but I think it would be a better idea to exchange the time dimension and the channel x frequency (resp. channel for /measurement/dataTD) dimensions.

As I see it the current specification has the drawback that
* it is quite inefficient to perform a frequency selection on /measurement/dataFD, since the channel x frequency dimension is sandwiched.
* it is also quite inefficient to perform averaging, since the time dimension is the slowest to access.

The only advantage I see is, that it is quite easy to transform from time to frequency domain.

In any case from my tests it is more easy to handle system functions than measurements. Then on the other hand keeping the time as slowest dim seems somehow natural.

**Comment by MandyA** [comment]
Hey there,

I'm a bit confused about your question. I get that you suggest to change the order of dimensions, but I don't actually understand which order you suggest. Further, from my point of view the time data in dataTD should actually be the fastest dimension, see e.g. this comment http://stackoverflow.com/questions/24116713/hdf5-rowmajor-or-colmajor (I currently can't find the HDF5 reference to this statement). So, I think the order of dims is quite good in terms of performance.

But maybe I got it worng, so would you be so kind to you specify your question? 

Best, Mandy

**Comment by hofmannmartin** [comment]
The issue here is, that depending on what you want to do with the measurement data it might be a bit tricky.

My main point is, that the order in which the dataFD is stored imposes how to reduce your data. That is you first have to select frames and perform averaging and such. Second, you might select certain frequencies from certain channels, which you need for reconstruction.

At the moment if you do it the other way around your code runs 100 fold slower. But in certain scenarios it might be a good idea to first select frequencies on your data, as you anyway just need some percent of your frequencies for reconstruction. But maybe we have to live with this, since it is on the other hand cumbersome to have 3 or 4 conventions on how to store dataFD.

Hope this makes things more clear.

**Comment by tknopp** [comment]
Martin and I discussed this offline and the consensus was that we should not change it. The current format is tailored to the way how the data comes in frames from the scanner.
@hofmannmartin: Please reopen if I got this wrong ;-)
