### ISSUE TITLE
MDF Working Group meeting at IWMPI

### ISSUE THREAD

**Issue by profix898** [MagneticParticleImaging/MDF#31]
I suggest that we schedule a meeting at IWMPI 2016 to discuss issues and future directions of the MDF exchange format and especially how to progress with open access to MPI datasets.
This way we could also invite other groups to join the initiative (or at least to be aware of it for now).

**Comment by hofmannmartin** [comment]
I think this is a great idea.

**Comment by gBringout** [comment]
I agree also!

--
Gaël Bringout

2016-02-25 19:27 GMT+01:00 Martin Hofmann <notifications@github.com>:

**Comment by tknopp** [comment]
Idea is great. I just fear that the time schedule is will be tough. Maybe we should beside discussions at IWMPI schedule a telco after IWMPI?

**Comment by MandyA** [comment]
Hey there,

I agree - the idea is very good, but tknopp has a point (I just had a look at the schedule...). I think we should take the opportunity to spread the word at IWMPI about MDF. I think we may find some time to discuss issues among people who already contribute. But a meeting with all interessted researcher will be a big challenge ;)

Best, Mandy

**Comment by hofmannmartin** [comment]
The IWMPI was a great meeting. Thanks to the organizers from Lübeck.
