### ISSUE TITLE
Further Cleanup of Examples

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MDF#32]
Dear @gBringout and @MandyA,

thanks for the recent cleanup of the Matlab Code. I still think we need more.
In my point of view the example directory should only contain three files

  README.txt
  kaczmarzReg.m
  pseudoinverse.m
  reco.m

like the Julia directory. Julia has additionally the sanityChecks.jl file there. We may move this to another directory although it is probably ok like it is now.

If you want to show images of the reconstructed data (or spectra) this should be put into the README.txt in the root directory of the MDF. The images could be put into an "images" folder, which are referenced in the README.txt file.

The point is that the data should look exactly the same for all three reconstruction codes. If no we have done something wrong ;-)

Cheers

Tobi

TODO for all those Pyhton hackers out there: Implement `pseudoinverse.py`

**Comment by MandyA** [comment]
Hey there,

I did the cleanup in the Matlab folder. Since the pyhton ToDo is stoll open I won't close the issue.
@gBringout I deleted the obsolete stuff. Hope, that's all right.
@tknopp I will implement sanity checks for Matlab.

Best, Mandy

**Comment by tknopp** [comment]
Thanks so much Mandy (@MandyA) . Looks very good now.
Decide on you own whether to implement the sanity check for Matlab. We will have to keep it in sync and while the examples are meant to be redundant, the sanity checks are rather enduser programs. But I am fine adding those. Just wanted to express that they are not so essential as the example scripts.

Other than that some proofreading / language improvements all over the github repo (but especially the spec) would be appreciated.

Cheers, Tobi

**Comment by gBringout** [comment]
Thank you Mandy!

--
Gaël Bringout

2016-02-29 11:36 GMT+01:00 Tobias Knopp <notifications@github.com>:

**Comment by tknopp** [comment]
- [x] Add SVD reconstruction for python example.
