### ISSUE TITLE
matlab function reco.m does not work

### ISSUE THREAD

**Issue by acbrandt** [MagneticParticleImaging/MDF#33]
Hi, 

I tried to test your matlab package, but the function reco.m is not running through, although Tobias added the function rowEnergy last week. You use the non-standard function csvd.m in line 64 which is missing in the repository. I tried to look for it with help of Google, but there are several m-files called csvd.m. Which one do I need? 

Christina

**Comment by gBringout** [comment]
Hi Christina,

I think that we forgot to correct the script when we cleaned up everythings.

The normal svd function should be used.

Let me know if it fixed the problem ( I can only test it myself this
evening).

Best,
Gael

--
Gaël Bringout

2016-03-29 9:07 GMT+02:00 acbrandt <notifications@github.com>:

**Comment by acbrandt** [comment]
Hi Gael, 

yes, this was the first thing which I tried myself. But in that case that I use svd instead, matlab stops in the next line (line 65) because inner matrix dimensions do not agree (line 19 in pseudoInverse.m). 

Christina

**Comment by gBringout** [comment]
ok, I will have to test that at home in the evening. Sorry about this
problem.

--
Gaël Bringout

2016-03-29 14:05 GMT+02:00 acbrandt <notifications@github.com>:

**Comment by gBringout** [comment]
I have solved the issue using the correct mod of matlab svd. replace the
csvd line by those two:

[U,Sigma,V] = svd(S_truncated(:,:).','econ');
Sigma2 = diag(Sigma);

Have fun,
Gael

--
Gaël Bringout

2016-03-29 14:08 GMT+02:00 Gael Bringout <gael.bringout@gmail.com>:

**Comment by tknopp** [comment]
Thanks Gael

**Comment by acbrandt** [comment]
Now I can run the file completely!

**Comment by gBringout** [comment]
You are welcome! Good to know that it is working!

Have fun,
Gael

--
Gaël Bringout

2016-03-31 10:02 GMT+02:00 acbrandt <notifications@github.com>:
