### ISSUE TITLE
Rename: `averages` -> `numAverages`

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#34]
This was proposed by Thilo and I must say, that I in agree, since all other fields which describe numbers also start with `num`.

We should make this change together with the next major update, which forces us to upgrade the version number to 2.0.0.

**Comment by tknopp** [comment]
in principle I am fine with that although such changes make it very difficult maintaining a library that can load various mdf versions

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
