### ISSUE TITLE
Problem with multiple diverse receive channels

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#40]
Consider the case were 2 receive channels measure at 2 different band width.

In this case the first channel has `K1` and the second `K2` frequencies, which need not be equal. How would one describe this case? As I see it the current specification only cover the case were all receive channels are identical.

I think we will have to perform a major update to resolve this issue
- Redefine K = K1+K2+...
- Redefine Z = Z1+Z2+...
- Replace CxK by K = K1+K2+...
- Replace CxZ by Z = Z1+Z2+...

What is your opinion about this issue?

**Comment by gBringout** [comment]
Why then not defining each quantitaties for each channel separetly?

--
Gaël Bringout

2016-06-08 17:52 GMT+02:00 Martin Hofmann <notifications@github.com>:

**Comment by tknopp** [comment]
Honestly I think that this use case is too unlikely to ever happen in practice. The receiver need to be highly integrated (they are fed by the same clock) and thus the sampling rate for all receivers will always be the same. Or was this concrete request by Thilo?

**Comment by hofmannmartin** [comment]
This request was on me.

**Comment by hofmannmartin** [comment]
Until this issue comes up in a practical use case I will close this issue.
