### ISSUE TITLE
Request of extending specific parameters for use with patches

### ISSUE THREAD

**Issue by MandyA** [MagneticParticleImaging/MDF#42]
We are currently changing our whole structure to MDF (simulation, measurement data, ...) and like to store more data in one file. This is mainly a request for MPS data that should be stored in one file. Therefore, we like to request the possibility to extend some parameters by one dimension. A good possibility I see is to use patches. As for several other fields it could be decided if the dimensionality is dependent on the number of patches. The following parameters would be affected:
- all parameters in group study or at least study/experiment, study/description, study/reference, study/simulation
- all parameters in group tracer
- parameter acquisition/time
- parameter acquisition/drivefield/averages
- parameter acquisition/drivefield/repetitionTime
- all parameters in groupd reconstruction

Do you have any comments, suggestions, ideas on that?

**Comment by tknopp** [comment]
Ok this is the hardest request ;-) 
I had already a short discussion with Anselm but will have to think a little bit more about this.

Just a very short comment: The idea of the format in its current form was not to allow storing multiple "measurements" into one file. So if you have an imaging protocol where you make multiple sequential measurements you would usually end up with one file per measurement. This is also how Bruker currently handles it.

Using the patches could be a workaround for what you have in mind but I would like to understand a little bit more the advantages of for instance using different tracers and storing it into just one file.

**Comment by MandyA** [comment]
Yes, this request actually comes from Anselm. The main idea is the following:

If a user makes different measurements with an MPS that belong to each other, we are looking for a nice way to indicating so. Of course, it might be a solution to store them in just one folder (current solution). But then we have to make sure that some data is consistent in the different files. It would be easier to have all measurements in one file. Same holds if we like to share the data - it is more convenient to have all the data in one file rather than split up in several. 

Possible scenarios are: different concentration of same tracer, different tracer material for same sequence, ... so it definitly goes in the direction of tracer characterization rather than MPI imaging. But of course we like to have a consistent format for all MPI related devices. 

I agree, the use of patches is a workaround I came up with, because I think it unlikely that someone want to have imaging patches and multiple measurements at the same time. However, it is not a nice approach, so I'm open for suggestions.

**Comment by profix898** [comment]
I would also argue strongly against multiple "datasets" per file. MDF is highly complex already from my point of view, especially because some fields support different/alternate array sizes, etc. I think that it gets increasingly difficult to open a MDF file without knowledge on the scenario it was created in. Multiple datasets just adds to this complexity. MDF was started to have a "simple" and "exchangeable" format between different MPI groups, and it is hard already to support it if it is not your "native" format (we try to import/export to MDF but store data differently otherwise).
And even in our internal format, we store one dataset per file (although the files for a given series of measurements are organized in a container/directory structure).

**Comment by tknopp** [comment]
I absolutely agree with @profix898.

I would argue the the solution with multiple files in a folder is not that bad. Having a high level organization of these files is indeed a challenging task that we also face in practice. But the solution to this is to create a database which can much better handle this. We work here in HH with "poor mans" database that relies on folder names and xml files.

While in principle patches could be used for it (feel free to try this!) I would recommend to also think about 3D MPS measurements where a single system function will already be several GB of data. Our largest system functions are of size 32 GB....

**Comment by hofmannmartin** [comment]
I also agree with @tknopp and @profix898. Using an organization structure on the data as proposed in #45 seems a solution which keeps the complexity of a single file at bay.

**Comment by hofmannmartin** [comment]
@MandyA can this issue be closed?
