### ISSUE TITLE
Question to defined parameters

### ISSUE THREAD

**Issue by MandyA** [MagneticParticleImaging/MDF#44]
I have some questions regarding parameters specified:
- I think in the documentation it is not clear if N in group reconstruction and N in groupd calibration have to have the same size. In particular, I think when using patches N might differ and can be different for different patches. I'm currently unsure what a good definition of N would be - any ideas?
- I have to admit that I'm not certain why there is the dataset acquisition/recevier/frequencies. Is it the correlation between frequency component and actual frequency? If so, I like to add a sentence in the description if you don't mind.

**Comment by tknopp** [comment]
> I think in the documentation it is not clear if N in group reconstruction and N in groupd calibration have to have the same size. In particular, I think when using patches N might differ and can be different for different patches. I'm currently unsure what a good definition of N would be - any ideas?

That is indeed true but actually N is just a derived parameter from size. And there are two different size parameters in the reconstruction and calibration group. Actually it would not make to much sense to have both groups into a single file. Either the file is a reconstruction file or a calibration file. But not both.

**Comment by tknopp** [comment]
> I have to admit that I'm not certain why there is the dataset acquisition/recevier/frequencies. Is it the correlation between frequency component and actual frequency? If so, I like to add a sentence in the description if you don't mind.

yes its the mapping `k` to `f_k`. Currently, it is a mandatory parameter since `K` is derived from it. The system how it is now would allow for frequency removal. Not sure if we need that but this was at least the motivation to have the parameter like they are now.

**Comment by MandyA** [comment]
> That is indeed true but actually N is just a derived parameter from size. And there are two different size parameters in the reconstruction and calibration group. Actually it would not make to much sense to have both groups into a single file. Either the file is a reconstruction file or a calibration file. But not both. 

> So it might be good to improve the documentation that `N` can mean different things (or I am also fine with renaming it to tilde(N))

Ok, I agree with that. But to be very clear for all MDF users I will change one N to tilde(N) as you suggested. 

But how do we handle patch data? Do we assume that all patches have the same size for reconstruction? For me this would be sufficient, but I think it might be a possible application. This is also related to another feature request, where I propose to add numPatches as a dimension to the reconstruction data. This might be usefull to store the individual reconstruction of patches. Now, when using several patches for imaging, the individual reconstructions have to be stored in different files.

**Comment by profix898** [comment]
I agree with @tknopp that having a frequencies vector might become handy in the future (and it is not too useless right now, I guess).

**Comment by hofmannmartin** [comment]
> Ok, I agree with that. But to be very clear for all MDF users I will change one N to tilde(N) as you suggested.

> But how do we handle patch data? Do we assume that all patches have the same size for reconstruction? For me this would be sufficient, but I think it might be a possible application. This is also related to another feature request, where I propose to add numPatches as a dimension to the reconstruction data. This might be usefull to store the individual reconstruction of patches. Now, when using several patches for imaging, the individual reconstructions have to be stored in different files.

I think we should use a completely different parameter like G instead of N. 
* As @MandyA pointed out in a multi patch reconstruction case the grid of the reconstructed data and system function might be different anyway.
* There might appear other cases where N is not equal to G in the future. So I think it is a good idea to completely loosen this restriction.
* We can mention in the documentation that G=N for the normal reconstruction, in which case the positions in the calibration group coincide with the positions in the reconstructions group.

I think the documentation should clarify that given a set of spatial positions Gx3 and a number of time steps L, for each position and time step the MPI value is provided. This value then can either be a scalar or a vector (length S).

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
