### ISSUE TITLE
Store Magnetic Offset Field for Calibration

### ISSUE THREAD

**Issue by AvGladiss** [MagneticParticleImaging/MDF#48]
When acquiring a system matrix, the positions of the sample are stored in /calibration/positions in m.

If a hybrid system matrix is acquired in a dedicated device or by a system calibration unit, the position in m is emulated by applying a magnetic offset field. I suggest to implement the parameter /calibration/offsetField in T for storing the applied offset field.
This parameter will allow for correcting approximation errors of the gradient field.

E.g. when acquiring a hybrid system matrix in a dedicated device and the gradient field of the scanner is approximated, an error is induced when storing the system matrix using /calibration/positions in m.
Using /calibration/offsetField in T without matching the desired grid (in m) of the scanner, the system matrix could be corrected for afterwards having gained further knowledge about the actual gradient field.

**Comment by tknopp** [comment]
Dear Anselm,
yes I think this sound like a very good idea. Could you make the changes in the tex file and either make a pull request or send me the updated file per mail?

Thanks.
