### ISSUE TITLE
Add TimePoint to /acquisiton/receiver

### ISSUE THREAD

**Issue by AvGladiss** [MagneticParticleImaging/MDF#50]
There is an optional dataset "frequencies" in Hz in /acquisition/receiver that maps the frequency data of e.g. /measurement/dataFD to the corresponding frequencies.
However, there is no corresponding dataset "timepoints" in s for e.g. /measurement/dataTD.

I suggest to implement an optional dataset /acquisition/receiver/timepoints in s that maps the recorded time data to the corresponding time points.

**Comment by tknopp** [comment]
Seems to make sense, although it would be interesting to know what this could be useful for.

**Comment by AvGladiss** [comment]
The dataset "timepoints" could easily be calculated by "numSamplingPoints" and "bandwidth", therefore it is not important to store it.
Therefore, I withdraw my request.
