### ISSUE TITLE
Storing Background Data

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MDF#51]
When we convert a Brukerfile into an MDF its not clear if we should store the BG subtracted system matrix or not. In Brukerfiles one can open both which is in my point of view too much data.

I think we should store the BG corrected data but should add another (optional) field containing a mean BG vector. This could then be used for reconstructing data where no BG measurement is available.

**Comment by AvGladiss** [comment]
I basically agree, but I think, a small alteration would make sense:
If the parameter emptyDataFD (or TD) exists in /measurement/ or /calibration/, then the stored data is corrected for the empty measurement. The dimension of the emptyData should be CxZ (TD) and CxKx2 (FD), respectively.
Additionally, if /receiver/transferFunction exists, then the stored data is corrected for its transfer function.

This way, the stored data is at the highest post-processing-level.

**Comment by tknopp** [comment]
ping @SzwarP @hofmannmartin. 

Martin, Patryk and I had a discussion about this one recently. I think we should talk about this on the phone.

**Comment by hofmannmartin** [comment]
We should

**Comment by AvGladiss** [comment]
Thank you for the discussion on the phone.
We talked about how to store the background data for a "/calibration" measurement, and I just realized that we did not discuss how to store the background data for a "/measurement". Will the specification of v2.0 include this matter?

**Comment by hofmannmartin** [comment]
For sure it makes sense to include this matter in the upcoming release. I will open a new issue for this. Thank you.

**Comment by tknopp** [comment]
@hofmannmartin made a draft that is now in the v2 branch. I think this looks good. The only thing I am not so happy about is that `N` is the last dimension for calibration data and `M` is the first dimension in the background data. We should think about this transposition a little more.

**Comment by hofmannmartin** [comment]
Did came across this issue as well.

We can discuss this tomorrow or on tuesday.

**Comment by AvGladiss** [comment]
Unfortunately, the v2 branch is still missing the background data for the /measurement-group.

As M relates to N, it should be at the same position, I agree.
Question: Will there be a parameter e.g. /backgroundPosition, where the spatial position of the background measurement is encoded?

We could think about creating a new group /background, where all the background information may be stored. This way, the /calibration and /measurement-group will not get too heavy and hard to handle.

**Comment by hofmannmartin** [comment]
What do you mean by spatial position of the background measurement?

**Comment by AvGladiss** [comment]
You are right, this was totally unclear. 
I did not notice until now that `dataTimeOrder` is [1,N+M]. I thought it was [1,N] and therefore, the link between `N` and `M` would be missing.

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
