### ISSUE TITLE
Store Phase of Drive Field

### ISSUE THREAD

**Issue by AvGladiss** [MagneticParticleImaging/MDF#52]
I suggest to store the phase of the applied drive field in /acquisition/drivefield/phase (Float64, Dim same as strength, Unit Degree).

**Comment by tknopp** [comment]
In this way we could even support Cosine excitations ... ;-)

**Comment by AvGladiss** [comment]
Exactly. Furthermore, if #53 is implemented, the phase dataset bears the information if e.g. a radial or spiral trajectory has been driven (as those only differ in phase).

**Comment by hofmannmartin** [comment]
We then should store angles in radian as it the appropriate SI unit.

**Comment by AvGladiss** [comment]
And we should agree on the limits [-pi,pi),

**Comment by hofmannmartin** [comment]
Any particular reason for this choice?

**Comment by tknopp** [comment]
its what is returned by the "atan2" function:  https://de.wikipedia.org/wiki/Arctan2 or what the "angle" function in Julia returns

**Comment by hofmannmartin** [comment]
In this case lets do it like this.

**Comment by tknopp** [comment]
fixed on v2 branch

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
