### ISSUE TITLE
Open MDF for different kinds of trajectories

### ISSUE THREAD

**Issue by AvGladiss** [MagneticParticleImaging/MDF#53]
When driving a lissajous-trajectory, the baseFrequency and its dividers can easily be stored in /acquisition/drivefield, as only one frequency per channel is driven.

When driving e.g. a radial or spiral trajectory, the magnetic field applied on one coil consists of multiple frequencies, e.g. when rotating 25kHz with 100 Hz, then the applied frequencies are 24.9kHz and 25.1kHz on each coil.

Therefore, I suggest to:
- implement /acquisition/drivefield/numFrequencies ("F") as a non-optional parameter defining the number of frequencies driven on each coil
- alter /acquisition/drivefield/divider to have the dimension D or DxF
- alter /acquisition/drivefield/strength to have the dimension D or DxF or JxD or JxDxF

**Comment by tknopp** [comment]
Yep, I think this is necessary. This is kind of a generalization of the "additionalFrequency" concept in IMT data format, right?

If we do this, drive-field phase should also be of the same dimension

**Comment by AvGladiss** [comment]
I have no further knowledge about the "additionalFrequency" in IMT data format.
The phase should indeed the same dimensions as strength then, because only then it is clear which trajectory have been driven.

**Comment by hofmannmartin** [comment]
Will the resulting excitation be of the following form?
![codecogseqn](https://cloud.githubusercontent.com/assets/7510025/26190912/0bef6ed4-3bac-11e7-8fc4-9fe385066400.png)

As I understand it these are the types of excitations the proposed extension will be able to handle.

**Comment by AvGladiss** [comment]
One may formulate the excitation as a product (e.g. 25kHz * 100Hz) as above or as a sum (e.g. 24.9kHz + 25.1kHz).
![grafik](https://cloud.githubusercontent.com/assets/22216765/26191702/38ffa9a4-3baf-11e7-9a1c-6ce0a3669265.png)

I would prefer to formulate it as a sum as this is easier in my experience.

**Comment by tknopp** [comment]
The sum notation is much more readable since this is the Fourier expansion of the excitation waveform

**Comment by tknopp** [comment]
One question: Should we make `sin` exchangeable, e.g. make it optionally a triangle function? Or additionally we could make this "custom" and then provide a buffer with the actual shape. (This API is used in the RedPitaya for example) I think this would make sense but it is slightly redundant with the above approach. But depending on the setting they are both handy.

**Comment by hofmannmartin** [comment]
So the idea is to provide the Fourier expansion of the excitation signal.

I think a custom signal just makes sense if the excitation signal has a non sparse representation in the Fourier domain. If this is the case it could be more convenient to  provide the signal shape and repetition frequency for each channel.

**Comment by tknopp** [comment]
fixed on v2 branch

**Comment by hofmannmartin** [comment]
Could you define the triangle function in the specs? Triangle might be a bit ambiguous otherwise.

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
