### ISSUE TITLE
Should each field have fixed Dimensions?

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MDF#54]
At the moment sever fields allow to have different dimensions, e.g. depending on the numPatches being greater than one.

We should think, if this is really practical, since it makes implementing the MDF more complex.

**Comment by AvGladiss** [comment]
In Luebeck we are finalizing our first implementation of the MDF and have introduced fixed dimensions for writing data.

**Comment by tknopp** [comment]
fixed on v2 branch

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
