### ISSUE TITLE
Allow dataTD to be stored as any

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#55]
I think we should allow time domain data to be stored as the user wishes. Just as we did for the Fourier data.

**Comment by AvGladiss** [comment]
Are you talking about the data type? I would prefer to introduces at least some restrictions, e.g. to allow only float64, int64 and int32.
For Fourier data, we could introduce the dataype float64, as int is not applicable here.

**Comment by hofmannmartin** [comment]
> Are you talking about the data type? I would prefer to introduces at least some restrictions, e.g. to allow only float64, int64 and int32.

As for the other data fields we make the assumption that the end user will not store data in a string representation. At the moment I see no reason to introduce a numerical type that choice of type.

> For Fourier data, we could introduce the dataype float64, as int is not applicable here.

Though this is very hypothetical by rescaling of my data I could store an approximation of my Fourier data as Integer values, though nobody would do so.

In my opinion we should keep the restrictions to a minimum.

**Comment by AvGladiss** [comment]
Just for clarification: Does "Any" mean you can choose between float64, int64 and string, or does "Any" give you complete freedom of choice (char, uint, bool, ...)?

**Comment by hofmannmartin** [comment]
Any allows to use any type supported by HDF5.

**Comment by tknopp** [comment]
yes but actually we want to restrict this to `Number` types. The issue is that we are not in a concrete programming language and therefore cannot use the nice type hierarchies available in certain programming languages (hint hint ...)

Since HDF just allows a certain number of types we may could report these here explicitly (Float16, Float32, Float64, Float128, Int8 - Int64). Until now we simply were too lazy to do this...

**Comment by hofmannmartin** [comment]
The upcoming version is a good opportunity to make this change.

In this case `Number` = {`H5T_NATIVE_FLOAT`, `H5T_NATIVE_DOUBLE`, `H5T_NATIVE_LDOUBLE`, `H5T_NATIVE_SHORT`, `H5T_NATIVE_INT`, `H5T_NATIVE_LONG`, `H5T_NATIVE_LLONG`}

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
