### ISSUE TITLE
Storing background data for measurements

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#58]
Should we include the possibility to store background data with every measurement. I.e. add the fields `/ measurement /backgroundDataFD` and `/ measurement /backgroundDataTD` or should we think of another solution? @tknopp @AvGladiss

**Comment by AvGladiss** [comment]
I think this would be a good idea!

As suggested in #51, we could define that measurement data is corrected for the empty measurement if the dataset /backgroundDataFD (or TD) exists. Furthermore, we could define that the measurement data is corrected for the transfer function as if /receiver/transferFunction exists.

This way, the stored data is at the highest post-processing-level.

**Comment by hofmannmartin** [comment]
The only problem is that this would be somewhat inconsistent, since we store the calibration data somewhat low level.

My suggestion would be to store the actual background measurement data (one frame should suffice).

**Comment by tknopp** [comment]
I think we should support storing BG measurements in the file. For MPS devices one usually acquires the empty measurement right before the actual measurement.

Regarding the level that is stored I vote for low level. In this way it is much more logical what is store in the file. I think the user will wrap the file loading primitives in an API where there is a simple flag (e.g. bgsubtration) and then it does not really matter that one has to subtract the BG.

Regarding the number of BG frames I would not restrict this. Let just keep this variable. This allows to derive background variance, which can be pretty handy.

**Comment by AvGladiss** [comment]
I finally agree on storing the data on a low post-processing level.

**Comment by hofmannmartin** [comment]
I will rework the measurement section to store measurement data and background today. Have an idea just now.

**Comment by AvGladiss** [comment]
As mentioned in #51,

> We could think about creating a new group /background, where all the background information may be stored. This way, the /calibration and /measurement-group will not get too heavy and hard to handle.

This way, we would have complete freedom of storing background data for both `calibration` and `measurement` and both the documentation and the groups would not be very heavy.

**Comment by hofmannmartin** [comment]
My idea is somewhat along this line but a little different.

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
