### ISSUE TITLE
Storing offset field positions for measurements

### ISSUE THREAD

**Issue by AvGladiss** [MagneticParticleImaging/MDF#59]
I suggest to introduce the dataset /acquisition/drivefield/offsetField (Float64, Jx3, T mu0^-1) as a non-optional field.

In e.g. an MPS, the FOV and FOV-center will always be a zero-value-dataset, but it is possible to apply offset fields to emulate a different FOV-center (same as in /calibration/offsetField).

As all the datasets stored in /acquisition/drivefield/ are non-optional, this new dataset should be non-optional as well.

As an alternative, I suggest to make fieldOfView and fieldOfViewCenter optional (and offsetField as well).

**Comment by hofmannmartin** [comment]
As i understand your request a shift of the FOV center is already covered in `/acquisition/drivefield /fieldOfViewCenter`. Or am I misunderstanding?

**Comment by tknopp** [comment]
I actually do not understand what the offsetField is about. Why did we do this? Only reason seems to be to be to define the field inhomogeneity (if available).

**Comment by hofmannmartin** [comment]
See #48

**Comment by tknopp** [comment]
I see. Yes that makes sense. We need some text explaining that either the positions or the offsetFields (in an MPS) were stored. Maybe a dedicated MPS section would be good since an MPS does not have a gradient field.

**Comment by hofmannmartin** [comment]
This should be the field at the position, where the delta sample was placed during the nth measurement for all measurements N.

> We need some text explaining that
:+1: 

> a dedicated MPS section would be good since an MPS does not have a gradient field.
:+1:

**Comment by tknopp** [comment]
But back to topic it would actually make sense to also store `offsetField` in addition to `fieldOfViewCenter`. In an ideal scanner they will be directly linked but in inhomogeneous fields not.

Its not clear if which one of both is optional. For our scanner we actually only can give `offsetField` since we currently do not know the other value. Maybe `fieldOfViewCenter` was too much looked from the reconstruction perspective where we would like to know this.

**Comment by hofmannmartin** [comment]
I think we will need both. For those who have a good understanding of the particular devive, where the data was measured `offsetField` would suffice. To be able to reconstruct MPI data we need `fieldOfViewCenter`. I am completely happy if both exist.

Maybe we explicitly state that the one is to use for MPS measurements and the other for MPI.

**Comment by tknopp** [comment]
fixed on v2 branch

**Comment by AvGladiss** [comment]
I think, a dedicated MPS section makes not too much sense, as the device itself is encoded yet in the /scanner group.
As explained in #62, I suggest to cope for these cases in a different manner.

**Comment by tknopp** [comment]
with section I did not mean a section in the parameter but a description within the main text, what is special about MPS measurements.

**Comment by AvGladiss** [comment]
I see, a thought you were suggesting an `/MPS` group. A text section would be a good idea!

**Comment by hofmannmartin** [comment]
@AvGladiss can you write this section after I have uploaded the next changes?

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
