### ISSUE TITLE
numPatches: where to solve the positions

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MDF#6]
from @MandyA:

1. There is a parameter numPatches and as I understand it several patches are stored consecutive in data. Is there already a possibility to store the individual positions (and sizes) of the patches?

**Comment by tknopp** [comment]
Yes the positions are stored in "/acquisition/drivefield/fieldOfViewCenter", the sizes are stored in "/acquisition/drivefield/fieldOfView"
You will see that all these parameters can be constant over a focus-field cycle or have to be specified for each FF position.

We wanted to keep the word "focus-field" out of all this, since it also can be realized by mechanical movement. For instance the Berkeley sequences are a combination of mechanical movement and FF movement.

Could you check if this now makes more sense?

**Comment by MandyA** [comment]
Yes, it does. I missed the parameter J entirely.
I will add this parameter in the remarks section of the acquisition group.
