### ISSUE TITLE
Moving /gradient to /driveField

### ISSUE THREAD

**Issue by AvGladiss** [MagneticParticleImaging/MDF#61]
I suggest to move the parameter /acquisition/gradient to /acquisition/drivefield/gradient.

Although the gradient is not part of the drivefield, it fits more into this section as it is strongly related to "strength" and "fieldOfView", "fieldOfViewCenter" and "offsetField". Furthermore, "offsetField" is not part of the drivefield either but is part of /acquisition/drivefield.

**Comment by hofmannmartin** [comment]
So maybe we should move `offsetField` to `acquisition` instead. Putting everything field related in just one spot could mess up the order, which was the idea of the subgroup in the first place.

**Comment by AvGladiss** [comment]
I see. Yes, maybe `offsetField` fits best into `acquisition` group then.

Then again, we could think about moving `fieldOfViewCenter` into `acquisition` group as well as it is directly linked to `offfsetField`.

**Comment by tknopp** [comment]
yes we have pulled many things into the DF group since there is a tight coupling. We often talk about the "drive-field FOV" but of course it is in the same way linked to the selection field and the focus field.

**Comment by tknopp** [comment]
If we start doing such massive changes it should be clear that MDF1 is obsolete. I think we can handle it, but this should be clear.

**Comment by hofmannmartin** [comment]
It was clear from the beginning that the upcoming version would not be backwards compatible. So we should use the opportunity for a little reorganization, wherever that makes sense.

**Comment by hofmannmartin** [comment]
Solved by the upcoming release of 2.0.0.
