### ISSUE TITLE
Define endianness of stored data

### ISSUE THREAD

**Issue by NeumannIMT** [MagneticParticleImaging/MDF#66]
Stored Datatypes should have a defined endianness. 
Using types like H5T_NATIVE_DOUBLE may save the data either in little or big endian depending on the used platform and thus create errors when using mdf files from a platform with a different endianness. 

 I would suggesst to default to datatypes with little endian ordering as most systems use little endian ordering. 
[https://en.wikipedia.org/wiki/Endianness](url)

**Comment by tknopp** [comment]
Thanks Alexander, lets use the little endian datatypes from

https://support.hdfgroup.org/HDF5/doc1.8/RM/PredefDTypes.html

Nowadays its close to impossible to find a big endian platform, so this is mostly a Documentation issue.

**Comment by hofmannmartin** [comment]
Fixed this issue with the latest update to the upcoming version.
