### ISSUE TITLE
Suggestion: Moving current group "/" to group "/file/

### ISSUE THREAD

**Issue by NeumannIMT** [MagneticParticleImaging/MDF#67]
Personally I think it is cleaner to move all file related information in its own group without litering the root of the file. It also helps to keep "/" clean because there may be more parameters concerning the file which could be added in later versions of mdf.

**Comment by tknopp** [comment]
Makes sense. I let Martin decide.

**Comment by hofmannmartin** [comment]
We should definitely keep this issue for a future update of the MDF which is as breaking as the transition v1->v2.

For now I think the three parameters stored in `/` are tolerable.

**Comment by hofmannmartin** [comment]
Since the aim is to keep compatibility post v2.0.0 we have to do it now or never.

I personally do not see a problem with having 3 parameters in `/` and I doubt that we will add many more.

Lets reach a decision: :-1: from me

**Comment by tknopp** [comment]
I am against moving this, because it makes v1 and v2 differ even more. We should only differ if we have good reason. 👎

**Comment by tknopp** [comment]
needs further votes from at least @MandyA @NeumannIMT @AvGladiss @profix898

**Comment by profix898** [comment]
uuid, version, timestamp are fine in root, why move them? 👎

**Comment by NeumannIMT** [comment]
> We should only differ if we have good reason.
> why move them? 

Maybe I should add a good reason: 
Its to avoid a breaking change in the future as mentioned by @hofmannmartin 

> We should definitely keep this issue for a future update of the MDF which is as breaking as the transition v1->v2.

If MDF ever needs more fileinfo in `/` we might really need to have a `/file/` group or we liter in `/` (which could be a real annoyance) and I just really want to avoid that breaking change in the future. (And it will be avoided as long as possible to not break anything so it starts with 4, 5 ,... , 17 parameters in `/`; Just playing devils advocate here) 

> I doubt that we will add many more.

We could specify that we are not allowed to add new datasets into `/` then this becomes a no issue

> I personally do not see a problem with having 3 parameters
> uuid, version, timestamp are fine in root, why move them? 

Just so you know: 
I personally also dont have an issue with having the current 3 parameters in `/` but I fear the possibility that more could be added to `/` in the future. 

Thats why I am for this proposal 👍 
or for specifying that no more parameters should be added to '/'

**Comment by tknopp** [comment]
In no way we will forbid ourself to add additional parameters in the future. Sorry, but if we need to add two new parameters to the root group, where is the problem? We don't want to win a contest for the most beautiful file layout here, but it should just work. @NeumannIMT: Please lets concentrate on real issues and not an subjective things. This will move us forward much faster.

**Comment by MandyA** [comment]
I am also against creating a new group for the three paramters 👎

**Comment by tknopp** [comment]
thanks for the input.
