### ISSUE TITLE
Suggestion: Remove redundant data (or make optional)

### ISSUE THREAD

**Issue by NeumannIMT** [MagneticParticleImaging/MDF#68]
There are a few Parameters which are redundant and can be easily obtained by checking the dataspace of well defined datasets. These are:

/acquisition/numPatches (J)
can be obtained from the following dimensions:  (only non-optional fields)
/acquisition/drivefield/strength 
/acquisition/drivefield/phase

/acquisition/numFrames (N) 
can be obtained from:
/measurement/data 
(assuming that acquisition group makes only sense if there is also a measurement group)

/acquisition/drivefield/numChannels (D)
can be obtained from the following dimensions:  (only non-optional fields)
/acquisition/drivefield/strength 
/acquisition/drivefield/phase
/acquisition/drivefield/divider
/acquisition/drivefield/waveform

/acquisition/receiver/numChannels (C)
can be obtained from:
/measurement/data 
(assuming that acquisition group makes only sense if there is also a measurement group)

it should be noted that the following dimensions are also not directly saved in the file: 
A - tracer materials/injections for multi-color MPI
O - acquired frames w/o background frames - [indirectly, /calibration/size but this information is needed]
F -  frequencies describing the drive-field waveform
U - sampling points describing a custom drive-field waveform - [optional dimensions]
W - sampling points containing processed data (W = V if no frequency selection or bandwidth reduction has been applied)
K - frequencies describing the processed data (K = V=2 + 1 if no frequency selection or bandwidth reduction has been applied)
Q - frames in the reconstructed MPI data set
P -  voxels in the reconstructed MPI data set [indirectly, /reconstruction/size but this information is needed]
S - channels in the reconstructed MPI data set

Necessary:
/acquisition/receiver/numSamplingPoints
but description of V seems to be of:
V - points sampled at receiver during one patch **(product of drive field period, numPeriods, numAverages)** - is the bold text correct? ()

**Comment by tknopp** [comment]
Not sure. Your Argument is valid and some are realy redundant. But reconstructed data actually does Container acquisition group.

Obtaining things from /measurement/data is doable but requires 2 if statements.

Martin?

**Comment by hofmannmartin** [comment]
We could get rid of J and D.

As for C and N we have to take into account that `/measurement/` is an optional group and all other fields which contain C are optional too. Thus we cannot easily get rid of them.

As for your last comment:
> but description of V seems to be of:
V - points sampled at receiver during one patch (product of drive field period, numPeriods, numAverages) - is the bold text correct? ()

At this point of the manuscript it is better not to refer to data fields, so I will update the description.

**Comment by hofmannmartin** [comment]
I decided to keep D and J. 

Since I can not get rid of C it would be inconsistent to get rid of D, since both are numbers of Channels. As for J it would be the only dimension of of `/measurement/data`, which is not explicitly stored (N, C, W), or can be directly derived (W->K).
