### ISSUE TITLE
Suggestion: Define complex datatype in HDF5

### ISSUE THREAD

**Issue by NeumannIMT** [MagneticParticleImaging/MDF#70]
Instead of giving the dataset an additional dimension to store the complex data create a definition for complex datatypes.

C++ example: (for float)
**new proposal compound type**
auto type_id_compound = H5Tcreate('H5T_COMPOUND',2*sizeof(float));
H5Tinsert(type_id_compound,"r",0,H5T_NATIVE_FLOAT);
H5Tinsert(type_id_compound,"i",sizeof(float),H5T_NATIVE_FLOAT);

**old proposal array type**
const std::array<std::size_t, 1> size{ {2} };
H5Tarray_create(H5T_NATIVE_FLOAT,1,size.data());

advantage: 
- no extra code needed to write std::complex<T> to a dataset (Can use same codepath as T, where T is any arithmetic type).
-  easier dataspace selection (reduced dimensionality, can also use same codepath as T)
-  memory is always sequentiell
-  /measurement/data can be read using the same codepath independt of if it is in time domain or frequency domain

disadvantage: Reading only one part (real or imaginary) is no longer possible. (Is this even wanted?)

**edit**: changed example to match discussion

**Comment by tknopp** [comment]
Could you show us how this can be done in Matlab/Python/Julia?

**Comment by hofmannmartin** [comment]
Reading a system function as a real matrix is indeed something one wants as many of the more advanced algorithms solving inverse problems assume real matrices.

Therefore, it is necessary to read the real and imaginary part.

**Comment by NeumannIMT** [comment]
In MATLAB one could do something like **(untested)**.

`function hdf5type = getHDF5Type(valtype)`
`if(isnumeric(valtype))`
`    if(isreal(valtype)) %% valtype is real`
`        %% Add more checks to return the actual type of val and not only double!`
`        % Copy the native type so that it can be closed without thinking`
`        hdf5type = H5T.copy('H5T_NATIVE_DOUBLE'); `
`    else %% valtype is complex `
`        %%Recursion to get the base type of val`
`        base_type_id = getHDF5Type(real(val));`
`        %%Create the Type `
`        typedims = [2]; % Complex has two values`
`        hdf5type = H5T.array_create(base_type_id, 1 ,typedims); `
`    end`
`else`
`    %% We could add a check here for strings and return the correct HDF5 type  `
`    error('Programming error! valtype must be of numeric type')`
`end`
`end`

I use a similar function in c++ to get the HDF5 type although it is more "templated" and does not do any comparison at runtime. 

Although I dont have experience in either Julia or Python and do not have time to learn the languages:
In Julia there is the command `h5t_array_create` to create an array type 
In Python it seems to boil down to define `dtype` correctly


> Therefore, it is necessary to read the real and imaginary part.

Do you need the ability to read the real and imaginary part seperatly? It only makes sense if you only use one part. If you still need both parts it is probably faster to read both together an then latter split them in memory instead of doing a seperate read operation for both using dataspace selections.

 Also datset Flag:` isFourierTransformed` can be deduced from the dimension of the dataset (or the stored datatype if we define the complex type).

**Comment by tknopp** [comment]
We do not need to read real part separately.

**Comment by hofmannmartin** [comment]
> Also datset Flag:`isFourierTransformed` can be deduced from the dimension of the dataset (or the stored datatype if we define the complex type).

That is true. The parameter exists more for reasons of consistency, such that each of the processing steps is explicitly documented, which make exploring the MDF with hdf5view or the like easier.

**Comment by tknopp** [comment]
Now that I have proper internet access I did some research on this. There are three different options to store complex data:
* add a new trailing dimension
* use a compound datatype (this is how pytables and octave do it)
* use an array datatype

All three are basically equivalent. The memory layout is exactly the same. One can `reinterpret` (in C/C++ speak `cast`) to the proper type. 

I don't really care which we use. I even like the compound datatype solution a little bit more. But there is on important thing. We need code for `Matlab`, `Python`, and `Julia` how to read an write such an array. Here is what we currently use:

https://github.com/MagneticParticleImaging/MDF/blob/v2/python/reco.py#L26
https://github.com/MagneticParticleImaging/MDF/blob/v2/julia/reco.jl#L22
https://github.com/MagneticParticleImaging/MDF/blob/v2/matlab/reco.m#L23

@NeumannIMT: I do not want to force you learning new programming languages. But there are people using all the three programming languages I listed and therefore it is mandatory that we have a simple example code for them.

**Comment by NeumannIMT** [comment]
Here you go: Matlab
```

clear all;

%% script to write complex data into a file using 3 different strategies!

%First creeate complex data:
cols = 3;
rows = 8;
nelems = cols * rows;

data = complex(zeros(rows,cols));
for n=1:cols
    for m=1:rows
        data(m,n) = complex(m,n);

% Initialize data. It is more efficient to use Structures with array fields
% than arrays of structures.
%        data_struct.real(m,n) = m;
%        data_struct.imag(m,n) = n;
    end
end

dims = size(data);

filename = 'MATLAB_HDF5_complex_test.h5';
datasetname = '/complex_1_test';

%% This does not work!
delete(filename);
%h5create(filename,datasetname,[2,dims]);
dims3D=[2,fliplr(dims)];
h5create(filename,datasetname,[2,fliplr(dims)]);
% Saves the data as double not as complex double 
% (I would consider this a bug in MATLAB!)
%h5write(filename,datasetname,data); 
h5write(filename,datasetname,permute(cat(3,real(data), imag(data)),[3 2 1])); 
%h5disp(filename,datasetname);
data2 = h5read(filename,datasetname);
data2 = squeeze(complex(data2(1,:,:),data2(2,:,:))).';
% Check the data!
if(~isequal(data,data2))
    disp('Naive: Data written is not the same as data read!');
else
    disp('Naive: Data written and read agree!')
end

%% Using array and compound types!!
datasetname1 = '/complex_array';
datasetname2 = '/complex_compound';

%fid = H5F.create('myfile.h5','H5F_ACC_TRUNC','H5P_FILE_CREATE','H5P_FILE_ACCESS');
fid = H5F.open(filename,'H5F_ACC_RDWR','H5P_DEFAULT');

type = 'H5T_NATIVE_DOUBLE';
type_id_array = H5T.array_create(type,2);


double_size = H5T.get_size(type);
type_id_compound = H5T.create('H5T_COMPOUND',2*double_size);
H5T.insert(type_id_compound,'r',0,type);
H5T.insert(type_id_compound,'i',double_size,type);

%Create the Dataspace
%space = H5S.create_simple(rank(data),fliplr(dims), []); 

% be aware that HDF5 is row major whereas MATLAB as column major order!
% This means that without extra care the data in the HDF5 will be 
% transposed compared to normal c-data layouts! (We go the extra mile here)
% uncomment lines for column major storage!
%space = H5S.create_simple(rank(data),fliplr(dims), []);  %column major
space = H5S.create_simple(rank(data),dims, []); %row major

%create the Dataset
dset_array = H5D.create (fid, datasetname1, type_id_array, space, 'H5P_DEFAULT');
dset_compound = H5D.create (fid, datasetname2, type_id_compound, space, 'H5P_DEFAULT');

%Close the space (we dont need it; will user H5S_ALL after that)
H5S.close(space);

% write the data to the dataset!
%H5D.write(dset_array, 'H5ML_DEFAULT', 'H5S_ALL', 'H5S_ALL', ...
%   'H5P_DEFAULT',[real(data(:)) imag(data(:)]'); %column major
H5D.write(dset_array, 'H5ML_DEFAULT', 'H5S_ALL', 'H5S_ALL', ... 
    'H5P_DEFAULT', reshape(permute(cat(3,real(data),imag(data)),[3 2 1]),2,[])); %row major

temp = reshape(permute(cat(3,real(data),imag(data)),[3 2 1]),2,[]);
H5D.write(dset_compound, 'H5ML_DEFAULT', 'H5S_ALL', 'H5S_ALL', ... 
    'H5P_DEFAULT', struct('real',real(data)','imag',imag(data).')); %row major
%   'H5P_DEFAULT', struct('real',real(data),'imag',imag(data))); %column major

%reshape(permute(cat(3,real(data),imag(data)),[3 2 1]),2,[]) is used to
%get from column major to row major storage. if you know a better way 
%please tell me !

%% will directly read it as an 2 x 8 x 3 array!
data2_array = H5D.read(dset_array, type_id_array, 'H5S_ALL','H5S_ALL','H5P_DEFAULT');
%data2_array = squeeze(complex(data2_array(1,:,:),data2_array(2,:,:))); %column major
data2_array = squeeze(complex(data2_array(1,:,:),data2_array(2,:,:))).'; %row major

data2_struct = H5D.read(dset_compound, type_id_compound, 'H5S_ALL','H5S_ALL','H5P_DEFAULT');
%data2_struct = squeeze(complex(data2_struct.r(:,:),data2_struct.i(:,:))); %column major
data2_struct = squeeze(complex(data2_struct.r(:,:)',data2_struct.i(:,:)')); %row major

% Check the data!
if(~isequal(data,data2_array))
    disp('Array: Data written is not the same as data read!');
else
    disp('Array: Read and Write agree!');
end

if(~isequal(data,data2_struct))
    disp('Compound: Data written is not the same as data read!');
else
    disp('Compound: Read and Write agree!');
end

%% Close everything!
% Close Datasets
H5D.close(dset_array);
H5D.close(dset_compound);

% Close types
H5T.close(type_id_compound);
H5T.close(type_id_array);

%Close file
H5F.close(fid);

```

**Comment by NeumannIMT** [comment]
here you go: Python (only compound datatype yet; dont know how to access low level hdf5 calls with python; but the current solution was ridiculously easy)

```
"""
Example to store and read complex data with HDF5
"""
import numpy as np
import h5py
import os

def run():
    """Function to run the example """
    filename = "Python_hdf5_complex.h5"

    cols = 3
    rows = 8

    #Generate Test data!
    complexdata = np.zeros((rows, cols), dtype=np.complex)

    for _n in range(0, cols):
        for _m in range(0, rows):
            complexdata[_m, _n] = np.complex(_m + 1, _n + 1)
            #print('Row:', _m, 'Col:', _n)

    print(complexdata)

    #delete old file
    os.remove(filename)

    with h5py.File(filename) as file:
        #Compound type (this one is very easy!)
        #Write the data!
        dset = file.create_dataset("complex_compound", data=complexdata)
        dset.write_direct(complexdata)

        #Read the data!
        complexdata2 = np.zeros((rows, cols), dtype=np.complex)
        dset.read_direct(complexdata2)
        print("Should be the same as above!")
        print(complexdata2)
  
if __name__ == "__main__":
    run()
```

**Comment by tknopp** [comment]
thanks. so its doable. But the code is much longer than our current version.

**Comment by hofmannmartin** [comment]
I also do not see any advantage over our one line of code, which currently handles complex data in matlab, python and julia.

**Comment by hofmannmartin** [comment]
Seems like the majority is against changes, so I am closing this issue.

**Comment by NeumannIMT** [comment]
> Seems like the majority is against changes, so I am closing this issue.

could a at least give me 24h hours to write an answer before closing. Also having more than 3 opinions would be good before deciding. (I don't mind if it is not in v2)

> But the code is much longer than our current version.
> I also do not see any advantage over our one line of code, which currently handles complex data in matlab, python and julia.

The reason it is one line of code is that you are relying on a higher level of abstraction to get the data and julia is basically missing that abstraction for complex types. Python does have it and there it is also one line of code! 
You could easily add it to Julia (approx. 10 line of extra code in HDF5.jl considering my 1h knowledge of Julia. The only thing I am missing are more information about the julia type system, overload resolution for the `write` function, template specializiation [although i think I figured that one out because it is similar to C++] and the `type:<concept` syntax) 
and BTW: You are relying on more than 1000 lines of supporting code to get that one liner ....
(I think i will steal the idea of HDF5.jl for attribute creation if the given hdf5 path is a dataset. I find it quite neat)

You will not see the advantage of defining a complex type as long as you are relying on the high level abstraction and a dataspace selection which is equal to `H5S_ALL`. As soon as want to have a more complex selection within the dataset you will need a different code paths for complex numbers due to the different dataspace definitions for complex and normal numbers. 
Furthermore the room for errors is decreased if a complex type is defined because it becomes impossible to split the dataspace between the real and imag part of the complex type.

To give you an example how my code looks. I have a function `write` looking like this: 
`std::enable_if_t<std::is_arithmetic_v<std::decay_t<T>> || stdext::is_complex_v<std::decay_t<T>> > write(const T& val) {...some code...}`
It can handle complex and normal arithmetic types the same way. Without a hdf5 type definition for complex type i need to split the function in two different functions due to the two different dataspaces needed. And the` write` function is not the only function where i would need two. I would also need it for every other type which can either hold a normal arithmetic type or a complex type. (Containertypes like array/vector, Eigen3 types, Dataspace selection types etc... ). 

Not defining a complex datatype now is in my eyes short sighted and will lead to a lot of headaches later on. Considering that python already allows directly writing complex types you could end up with people saving complex data however they like because it is more convenient to do so. It is also more convenient to handle dataspace selection with normal and complex numbers in the same why and thats the reason I want to have a complex datatyp or be allowed to use one in MDF. 
(Furthermore, I gave you all the code need to read and write such a dataset.)

Would be nice to have Thilos (@profix898) opinion on that one since he seems to have some knowledge of generic programming in c#

**Comment by tknopp** [comment]
ping @AvGladiss @MandyA (see above, opinions wanted)

**Comment by tknopp** [comment]
We are in the process that we want to finalize v2.0. It might not be obvious but we have a serious time pressure behind this since we are already using/generating v2.0 data in one of our scanners.

**Comment by hofmannmartin** [comment]
> Would be nice to have Thilos (@profix898) opinion on that one since he seems to have some knowledge of generic programming in c#

@NeumannIMT See #71 @profix898 wrote this as a reply to one of your comments:

> Using a compound type for complex (#70) could be discussed, but I'm also strongly against replacing groups with compound constructs.

As this issue seems to be a big concern for those using static languages I agree to change the MDF specification post v2.0.0. It should also be quite simple to write a small script uplifting all v2.0.0 files to the next version including these changes.

@tknopp would you be able to make the changes to `HDF5.jl` required for this if the time comes?

**Comment by profix898** [comment]
I did a quick review on complex-valued data handling in HDF5.

**Matlab**: H5T_COMPOUND is not supported by the Matlab high-level HDF5 functions, only via low-level functions.
**Octave**: Uses ("real", "imag") compound type by default for complex-valued data
**Python**: PyTables uses ("r", "i") with fallback to ("real", "imag") compound type (numpy style)
**Mathematica**: Supports compound types, but doesnt use them by default for complex-valued data

https://support.hdfgroup.org/HDF5/doc1.6/UG/03_Model.html with complex compound example
```
Typedef struct {
       double re;   /*real part */
       double im;   /*imaginary part */
    } complex_t;

    complex_t tmp;  /*used only to compute offsets */
    hid_t complex_id = H5Tcreate (H5T_COMPOUND, sizeof tmp);
    H5Tinsert (complex_id, "real", HOFFSET(tmp,re),
               H5T_NATIVE_DOUBLE);
    H5Tinsert (complex_id, "imaginary", HOFFSET(tmp,im),
               H5T_NATIVE_DOUBLE);
```

I searched several sources (incl. stackoverflow/stackexchange, matlabcentral, HDF5 mailing list on nabble, etc.) and it seems that there is no consensus on how to store complex-valued data in HDF5. Most people suggest to store re/im parts (separately) as real-valued arrays to maximize compatibility (since HDF5 doesnt provide a native 'complex' type). This is also what we do now in MDF.
Having a complex type in MDF would certainly make things easier for us in C-land. I see the biggest advantage with regards to the hyperslab feature. Still, I'm not sure this outweighs the possible compatibility issues, which are hard to foresee for me right now.
I tend towards our current solution of adding a trailing dimension or even storing re/im separately. But if we decide to change this, we should really do so before final 2.0 is released. And we really need additional feedback (Lübeck, Würzburg, Aachen?) to decide here.

**Comment by tknopp** [comment]
I am currently trying to get the compound version to work, but I am facing issues with mmap. We usually mmap the array and only load individual rows into main memory. I think this is similar to the hyperslabs you mentioned.

**Comment by profix898** [comment]
Hyperslap is a HDF5 feature to write/read only a subset of a dataset.
https://support.hdfgroup.org/HDF5/Tutor/selectsimple.html
https://support.hdfgroup.org/HDF5/Tutor/select.html
https://support.hdfgroup.org/HDF5/Tutor/phype.html

Anyway, the trailing dimension from our current spec requires special handling for all complex-valued datasets. As @NeumannIMT mentioned, with a compound type all the custom logic would be gone and we could use the same selectors as for all 'native' HDF5 data types. (The more I think about it, the more I like the idea ...).

**Comment by tknopp** [comment]
yes mmap allows to do the same as the hyperslab. We pin the entire matrix to memory and then can access slices `A[:,:,:,k]`.

**Comment by tknopp** [comment]
Ok, I have now implemented the compound solution and I think I can live with it. Here are the changes in MPIFiles.jl:

https://github.com/MagneticParticleImaging/MPIFiles.jl/commit/d762c952934cd076ffa4ba09834b9b26fb435048

Here are the changes in the Julia example code:
https://github.com/MagneticParticleImaging/MDF/tree/v2/julia

@NeumannIMT: Could you please update the Matlab and the Python example. I would further appreciate if you could update the specification to include this. Either make a pull request or just send me the updated files (by email) and then I will merge them.

**Comment by tknopp** [comment]
@NeumannIMT: I use `r` and `i` for the field names since this is how `h5py` does this (and the example in the official HDF documentation.

http://docs.h5py.org/en/latest/config.html

Are all fine with this?

**Comment by NeumannIMT** [comment]
h5py actually reads a configuration file to figure out how the fields should be named (looked in the source for that knowledge in the morning)

I am fine with r and i. real and imag would also be ok. I think it just matters for the MATLAB implementation to access the structs (and maybe for python). The low level HDF5 implementations will most likely not care about the actual field names and just compare datatypes and do a direct mapping between fields (at least I hope so).

**Comment by tknopp** [comment]
ok, than lets just do this. Remaining work item is updating the specification. And please talk with @AvGladiss and @MandyA about this change.

**Comment by AvGladiss** [comment]
I looked at it today and liked it!

**Comment by tknopp** [comment]
thanks Anselm, then this can be closed since the majority likes it and the specification i already updated.
