### ISSUE TITLE
Question: String data: Fixed size or variable length?

### ISSUE THREAD

**Issue by NeumannIMT** [MagneticParticleImaging/MDF#73]
Should strings be fixed size strings or variable length strings? Or do we have a mix of both in mdf?

I believe we need variable length strings if we want to store an array of strings. The reason for that is that the array needs a common type and having fixed size strings means having a different type for each array element because the size is part of the type.
 
Does anybody have experience with storing strings to hdf5 using fixed size strings in an array?
Should the mdf spec define strings in more detail? There is another disadvantage of allowing both: Different code paths are needed to read/write them. 

(I am currently using only variable length strings in my hdf5 code and it works fine. )

**Comment by hofmannmartin** [comment]
Though not explicitly documented we use variable length strings only. 

@tknopp did we store an array of strings yet?

**Comment by tknopp** [comment]
String arrays are variable length. Regular strings are not restricted. We do not restrit datatype's if not necessary.

Please have a look at our example data.

**Comment by tknopp** [comment]
We try to let the datatype be as generic as possible. For this reason one has to check, which datatype is actually contained in a dataset (see `Integer` and `Number` definitions). I am not sure why we should make an exception for Strings.

**Comment by profix898** [comment]
> We try to let the datatype be as generic as possible. For this reason one has to check, which datatype is actually contained in a dataset

You are living in a dynamic world with Julia/Matlab. For everyone in a strongly-typed language the variability you were talking about is a pain in the ... (especially because HDF5 performs automatic conversion if one reads data with a different numeric type/format). I'd be very happy to see this (and some other similar details) be specified/fixed in the MDF spec.

**Comment by tknopp** [comment]
yes indeed this is basically for free for dynamic languages. I am just not sure what to do. measurement data makes sense in Int8, Int16, Float32, Float64. So what to choose?

**Comment by tknopp** [comment]
And in the particular case: Isn't it exactly the same code how to `read` a fixed-size or a variable size string?

**Comment by tknopp** [comment]
@profix898: Martin and I set down and removed most of the variability of parameters (where it is not necessary). There are now just two `Number` fields, where we need the variability. Could you please check and confirm that this is now better?

Regarding Strings my question remains. fixed-size and variable-size strings can IMHO be read by the same code path so that I do not see why we should restrict this.

**Comment by NeumannIMT** [comment]
> Regarding Strings my question remains. fixed-size and variable-size strings can IMHO be read by the same code path so that I do not see why we should restrict this.

It may not matter for your high level julia abstraction of the HDF5 but just an example for reading the data in c++. 
```
C++ Reading:
		template<typename CharT,typename TraitsT, typename AllocatorT>
		auto readData(std::basic_string<CharT, TraitsT, AllocatorT>& val, const HDF5_MemoryOptions& memopts = HDF5_MemoryOptions{}, const HDF5_DataspaceWrapper& storespace = HDF5_DataspaceWrapper{}) const
		{
			const auto type = getDatatype();
			const auto size = type.getSize();
			if (size == sizeof(char *)) // => variable length string!
			{
				//If an exceptions is thrown between the lines we will leak memory (The HDF5 part)!
				//char **rdata = (char **)malloc(sizeof(char *));
				std::unique_ptr<char *> rdata(new char*);
				const auto err = H5Dread(*this, memopts.datatype, memopts.dataspace, storespace, mOptions.transfer_propertylist, (void*)rdata.get());
				val = *rdata; //Copy the const char* into string object. May throw if not enough memory is available!
				H5Dvlen_reclaim(type, memopts.dataspace, H5P_DEFAULT, (void*)rdata.get());
				//free(rdata);
				return err;
			}
			else // => fixed size string
			{
				val.resize(size);
				return H5Dread(*this, type, memopts.dataspace, storespace, mOptions.transfer_propertylist, val.data());
			}
		}
```
On which I can build a higher abstraction like this: (example reads the date string from an mdf file and it does not matter wether it is fixed size or variable length)
```
	{
		std::experimental::filesystem::path path2{ "measurement_5.h5" };
		using TestInput = Archives::HDF5_InputArchive;
		TestInput In{ path2,{} };
		std::string date;
		In(Archives::createNamedValue("date", date)); // Maybe allow In({"Fieldname",Fieldvalue}) in the future
		std::cout << "Date is: " << date << "\n";
	}
```

If I want to write the data I have to chose either a fixed size type or the variable type dependend if the dataset is a simple dataset or a scalar valued dataset. If i can just write the data always using variable length strings I am fine with it. I dont know if it will have side effects in Julia, Python or Matlab. It could be handled by the abstraction layers of those languages as well but I am not sure about that and thats the reason why I ask. 

But from this comment 

> Regarding Strings my question remains. fixed-size and variable-size strings can IMHO be read by the same code path so that I do not see why we should restrict this.

It seems that at least for Julia to be ok.

**Comment by tknopp** [comment]
> Regarding Strings my question remains. fixed-size and variable-size strings can IMHO be read by the same code path so that I do not see why we should restrict this.

I was referring to the C API. I am not sure why you have to special case the variable length string. The H5Dread call is pretty much the same.

In Julia/Python/Matlab one can read both fixed-size and variable-length Strings.

**Comment by NeumannIMT** [comment]
H5Dread for variable length string needs a pointer to a pointer of char -> meaning char**
H5Dread for fixed size strings needs a simple pointer of char -> meaning char*

The reason for this is that the HDF5 API is creating the memory space for the char buffer in the case of the variable length string because the user does not know how big the string in the file is. Memory is managed by HDF5 and string needs to be copied to Memory managed by the User. (How HDF5 deduces the size of the string is hidden behind implementation details of HDF5)
In the case of the fixed size string I can directly ask HDF5 how big the string is. In this case the User is directly able to Manage the Memory.  

> In Julia/Python/Matlab one can read both fixed-size and variable-length strings.

If this is possible without any side effects just allow both and let the implementation decide wether it uses fixed size or variable length strings.

**Comment by tknopp** [comment]
strange API decision. But anyway you have a good implementation for reading both String types such that this issue can be closed.
