### ISSUE TITLE
MATLAB: FFT of integer datatype does not work.

### ISSUE THREAD

**Issue by NeumannIMT** [MagneticParticleImaging/MDF#78]
FFT in MATLAB seems to only work on floating points types. The current example thus does not work. I could simply cast it to double but is this the desired behavior?
(using MATLAB R2016b)

**Comment by tknopp** [comment]
It did work on a Matlab version that we once used (we do not have matlab here, but a student once had a version here so that we could test.

But anyway. Lets just cast. Your fix is perfect. Closing this.
