### ISSUE TITLE
define default values for (optional) flags 

### ISSUE THREAD

**Issue by NeumannIMT** [MagneticParticleImaging/MDF#86]
It is not specified but has to be.  
(yeah i know it is obvious)

**Comment by hofmannmartin** [comment]
This should be done before we release v2.0.0.

**Comment by NeumannIMT** [comment]
just to speak it out: default to false or allow defining other values within the MDF spec?

**Comment by hofmannmartin** [comment]
The optional flags in the `measurement` group are all false by default.

As for the `isOverscanRegion`: The absence of this field should indicate that the mask is unknown.

**Comment by tknopp** [comment]
I don't fully get it. If a parameter has a sensible default, we should make it non-optional. Only those parameters should be optional, where it is not possible to set a sensible default. `injectionTime` is such an example.

We should probable make more parameters non-optional. `isbackgroundFrame` could be non-optional.

**Comment by hofmannmartin** [comment]
If we allow make extensive use of `NaN` (give it the meaning of unknown values) we could in principle make every field of element type `Float64` non optional. On the down side we would bloat the MDF with a lot of useless data. To minimize the data overhead and keep MDF files small these optional fields are not that bad. Plus if certain optional fields are not required they can be simply ignored in the implementation.

Opinions?

**Comment by tknopp** [comment]
ok, it seems we have agreement here -> someone has to update the specification.

**Comment by hofmannmartin** [comment]
I will.
