### ISSUE TITLE
Redefine the term Patch

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MDF#87]
Martin and I make the following proposal:

1. The term `numPatches` was suboptimal for what we describe here. We propose to rename it to `numPeriods`. The current `numPeriods` are removed. A `frame` than is a collection of `numPeriod` drive-field cycles.
2. ~~The term `numPatches` is reintroduced in a new form and it describes the number of different configurations (drive-field amplitude/phase, gradient, offsetFields) that are contained in a certain sequence. Most fields that are depending on `J` are then depending on this value. Lets name it `R` for the moment.~~
3. ~~There is a (non-optional) indexMapping `/acquisition/indexFieldConfiguration` that allows us to map a certain drive field period to a certain field configuration.~~

~~In principle we could also only do 1. but then it would be some manual work to determine the number of different field configurations that were applied.~~

Updated

**Comment by NeumannIMT** [comment]
A bit more context would be good. 
So the new `numPeriods` would have the description of the current `numPatches`? Which would be:
`numPeriods` : Number of patches within a frame denoted by J
The description does not sound right. How would you change it?

**Comment by tknopp** [comment]
@NeumannIMT: ??? Don't know what you mean by description. We of course have to change several of the wording within the specification.

numPeriods: Number of periods with a frame. Each period can have a different field configuration.

**Comment by NeumannIMT** [comment]
> We of course have to change several of the wording within the specification.
> numPeriods: Number of periods with a frame. Each period can have a different field configuration.

Ok, maybe I was confused by your wording in the proposal. From how I read it it was: "Change just the name of the parameter numPatches -> numPeriods without changing anything else."

Still a bit more context would be good if you want to have an open discussion: 
Why is the current design suboptimal and how does the current proposal make it better?

**Comment by tknopp** [comment]
@hofmannmartin: Discussed this today with Patryk and we directly had the issue how to express dynamic focus fields. One way is to use the custom Waveform and use the drive fields for describing the focus fields. But this feels kind of a hack.

The other option is to let `offsetFields` and `gradient` to be a parameter that may have a finer temporal resolution than one DF cycle. This feels more promising.

**Comment by tknopp** [comment]
But in that case the indirect Mapping is not feasible anymore. But IMHO this is not such a big issue.

**Comment by hofmannmartin** [comment]
> The other option is to let offsetFields and gradient to be a parameter that may have a finer temporal resolution than one DF cycle. This feels more promising.

Seems to be a good idea. Will think about a solution

**Comment by AvGladiss** [comment]
I do not fully understand this.

The previous idea was, that we aquire `numPeriods` of one drive-field cycle (e.g. in the Bruker-Scanner, we choose a 2D trajectory but only excite in one direction [12,0] - then we have `numPeriods`=16 e.g.).
These `numPeriods` may be averaged by `numAverages`. This means that we do not average over 1 period, but over `numPeriods` periods - this is an important difference, as the time resolution of the signal is different.
Then, we may change the offset/focus/drive/selection fields and begin a new patch.
In the end, we have one frame that may be acquired again.

As I understand it correctly, `numPeriods` would be omitted?

**Comment by tknopp** [comment]
yes remove `numPeriods` and instead use `numPatches` for that. The important point is that this allows to measure different number of periods at different patch positions.

For instance: If you measure 10 periods per patch and have 4 patch positions, you will have 40 drive-field periods.

We do not really loose anything here, but there are then not 2 different ways to express the same thing.

**Comment by tknopp** [comment]
And pleas have a look at #93 where this goes one step further when we allow for continuous FF movements.

**Comment by tknopp** [comment]
I merged an updated version of #93. We now have

`numFrames` and `numPeriodsPerFrame`

The term `Period` here and in general refers to an averaged drive-field period (`numAverages`).

One additional thing. One may now also use

`numPeriods` = `numFrames` * `numPeriodsPerFrame``

We don't do this in the document (since it is not needed) but in a library code one may not care if periods are in a specific focus-field cycle.

**Comment by tknopp** [comment]
I am closing this. Feel free to reopen if thing are not clear (or you are not satisfied).
