### ISSUE TITLE
Define naming convention for flags.

### ISSUE THREAD

**Issue by Neumann-A** [MagneticParticleImaging/MDF#88]
The spec should define a naming convention for boolean flags (see also discussion in #74). Currently mainly `isSomething` is used to describe something. My proposal is to use `is` flags for data changing/describing flags like background correction, transfer function correction etc. whereas to use `has` flags for dataset describing attirbutes like frame ordering, etc. Both indicate boolean meaning but it adds a little bit of syntatic sugar to say more than that:

`isSomething` : Be carefull something has been done to the data directly which might screw up your reco
`hasSomething` : Be carefull something has been done with the order of the data which might screw up your reco

**Comment by hofmannmartin** [comment]
There are two more flags outside the `/measurement` group, which start with `is` but are not related to anything done with the data. If the syntactic meaning is important we would need to do something about them too. Suggestions?

**Comment by NeumannIMT** [comment]
The flags are:
`isSimulation` in /experiment/: Could also be called `isSimulatedData`, so also data describing
`isOverscanRegion` in /reconstruction/: That one is definitly data describing so no issue here. (The data being /reconstruction/data not measurement/data;) It has the same semantics as 'isBackgroundFrame'

my example with: "might screw up your reco" could be a bit to narrow for what I really meant

**Comment by hofmannmartin** [comment]
> my example with: "might screw up your reco" could be a bit to narrow for what I really meant

If you would find a more general description I would be fine with the change.

If no further objections come in, I will assign you to make the changes within the mdf.

**Comment by NeumannIMT** [comment]
> If you would find a more general description:

More general would be: "might screw up your interpretation of the data". I wanted or more application near example thats why I chose "might screw up your reco"

> If no further objections come in, I will assign you to make the changes within the mdf.

Ok, will wait till monday to see if there are any objections. Should the change include the outcome of the late discussion in #74

**Comment by hofmannmartin** [comment]
> More general would be: "might screw up your interpretation of the data". I wanted or more application near example thats why I chose "might screw up your reco"

Since we do not know what the user does (could not always be a reconstruction), I find it more appropriate to simply give the user a hint that this and that has to be taken into account when interpreting the data.

**Comment by tknopp** [comment]
I don't understand the issue that is solved here. `is` just indicated a boolean. It has nothing to do with reco. Using `is/has` to indicate `order change` or `data change` is completely arbitrary and has no linguistic motivation.

Either we check each flag and look what sounds more appropriate, or we live with the current scheme. I do not care! If this is important for @NeumannIMT please just rename the flags.

**Comment by tknopp** [comment]
This has not been changed in v2.0. We live with some linguistic hiccup but apply a simple scheme where `is` indicates a boolean parameter
