### ISSUE TITLE
Parameter extensions needs overhaul

### ISSUE THREAD

**Issue by NeumannIMT** [MagneticParticleImaging/MDF#91]
the current specification basically allows everything in terms of adding parameters. There is currently only  recommandation how to name parameters/groups. 
I think that is a really bad idea and can lead to major headaches if the user has a already named group/dataset and an MDF extensions decides to take that name (name clash).

My proposal is thus to add a group /detail/ where the user can add any parameters he wants and MDF promises not to screw with the group or anything in it.

**Comment by hofmannmartin** [comment]
I do not want to be too restrictive. Sometimes you want to add additional information and group it with whatever you want to provide the information for.

As a compromise I would rather make the recommendation a rule.

**Comment by NeumannIMT** [comment]
/detail/ would be allowed in any group ... maybe should have written <anygroup>/detail/ 

> As a compromise I would rather make the recommendation a rule.
 
i dont like uglyfied names. If reflection comes to C++ I would rather have my variables clean of any leading "_" because it is reserved for library implementations (although it can be used without restriction).

**Comment by hofmannmartin** [comment]
we could also use variables with leading `UD` for user defined.

**Comment by NeumannIMT** [comment]
> we could also use variables with leading UD for user defined.

Would be somewhat ok, although if i use reflection for variable names i would have to name my variable all UDSomething which feels unnatural.

How about allowing both:
<anygroup>/detail/ for people who dont want to have the UD prefix 
and the requirement for UD for everybody else.

**Comment by hofmannmartin** [comment]
Could live with that.

`/detail/` would be used to store multiple fields and `UD` would be more convenient for a single one.

**Comment by NeumannIMT** [comment]
from my perspective /UDGroupname/ would also be ok to store multiple fields.

So conclusion:
allow /detail/
allow /UDGroupname/
allow UDDatasetname

disallow everything else for users?

**Comment by hofmannmartin** [comment]
> just found out that anything writen in < > is invisible

I do not see any advantage. You should be able to explore MDFs.

> disallow everything else for users?

yes

Will assign you to this one too, if there are no objections.

**Comment by NeumannIMT** [comment]
> I do not see any advantage. You should be able to explore MDFs.

was not related to MDF but Github. Try writing anything in \< \> on a github issue and the text inbetween vanishes if not escaped with \\: Example: <IamInvisible> (Escaped: \<IamInvisible\>)

**Comment by tknopp** [comment]
I do not support this. The reason is that we have 1000 files that are in production use, where the parameter `/reconstruction/_parameters` is used. Using `_` solves exactly the name clash problem.

**Comment by NeumannIMT** [comment]
> I do not support this. The reason is that we have 1000 files that are in production use, where the parameter /reconstruction/_parameters is used. Using _ solves exactly the name clash problem.

I dont see any problem with exisiting files. It should just affect new files. 

"_" is simply a bad idea. Here are some reason:
Julia: discourages the use of _ in variable names (see: [Source](https://docs.julialang.org/en/stable/manual/variables/) at the end of the section)
C++: _ is a (partial) reserved token for identifiers (see: [Stackoverflow](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier))
MATLAB: does not allow creation of variables starting with an _ 

So and if you are like my and not manual defining your fieldnames in code you dont want to be bound to using _. Let me come up with a good wording for the spec before judging the proposal.

**Comment by profix898** [comment]
My vote for keeping `_`. As Tobias said it solves the naming issue and nicely marks user-/problem-specific variable names. Also, from my point of view, `_myVar` is more apparent/obvious - you can spot it at first sight - than `UDmyVar`.

I think we allow both datasets and groups to use the `_` convention. So you can already introduce subgroups like `/measurement/_details/` for your convenience.

> i dont like uglyfied names. If reflection comes to C++ ...

@NeumannIMT Just out of curiosity, do you plan on rewriting all your existing code to align with MDF naming conventions? I mean, every MPI group has developed a certain codebase over the years, which - for sure - is incompatible with MDF naming (simply because MDF didnt exists at development time).
If we decide (for good reason) to alter names in MDF would you adapt your implementations? In the long run, I think an 'adapter' approach is more viable and maintanable, especially because some scenrios are not covered by MDF yet. So the internal code comes first (probably with `_` names), and then we think about incorporating it into the MDF spec.

**Comment by profix898** [comment]
> So and if you are like my and not manual defining your fieldnames in code you dont want to be bound to using _.

For the `_` version you have to rename from `_myVar` to `myVar` once this is an accepted addition to the MDF spec. With the `/details` approach, you move from `/x/details/myVar` to `/x/myVar/` (or even into `.../newGroup/myVar`). So where is the advantage? In both cases you have to treat non-standard parameters/variables special.

**Comment by tknopp** [comment]
> Julia: discourages the use of _ in variable names (see: Source at the end of the section)
> C++: _ is a (partial) reserved token for identifiers (see: Stackoverflow)
> MATLAB: does not allow creation of variables starting with an _

I don't understand what a variable name in a programming language has to do with the name within an HDF5 file.

**Comment by profix898** [comment]
> I don't understand what a variable name in a programming language has to do with the name within an HDF5 file.

Nothing, unless you enforce a 1:1 mapping or data binding as @NeumannIMT apparently does (by generically mapping the fields to variables).

**Comment by NeumannIMT** [comment]
> For the _ version you have to rename from _myVar to myVar once this is an accepted addition to the MDF spec

If MDF is to be considered stable this should happen very rarely. 
maybe we could adopt something from c++ where experimental stuff is in std::experimental before it is moved into std (new issues for group /experimental/ for things which might become part of MDF?)

> If we decide (for good reason) to alter names in MDF would you adapt your implementations? In the long run, I think an 'adapter' approach is more viable and maintanable

Yes I would do it with my code because the spec would be part of the codes documentation. Dont forget that the adapter will most likely also need variablenames to store some flags or similar things.
Of course I would only adapt if I consider MDF stable and expressive enough. (But thats what we are working on right?)

> So where is the advantage?

Instead of removing _ from all variable I could just remove the additional path in the implementation.
Changes needed: Number of variables ( _ version) vs. 1 (/detail/ version)

> I don't understand what a variable name in a programming language has to do with the name within an HDF5 file.

In C++ I can write a macro which gives me the name (as a char array) of a variable. In Julia you can do the same. So if you change the variable name the string representation also changes. Its a very convient feature if you dont want to refactor your code everywhere, when you change the meaning of a variable and it gets a new name. 

**Lets step back a bit from details:**
Do we agree on the fact that we need to change the current spec to something which is more restrictive concerning parameter extensions to avoid future name clashes?

Maybe I a should rephrase my standpoint: I am not against you using _dataset or _group for your custom parameters or groups but please dont force me to also use it. 

My proposal is thus:
allow anygroup/detail/
allow anygroup/_groupname/
allow anygroup/_datasetname/

**Comment by tknopp** [comment]
> Maybe I a should rephrase my standpoint: I am not against you using _dataset or _group for your custom parameters or groups but please dont force me to also use it.

What? Why should we force you to use a private parameter we use. Just ignore it.

**Comment by AvGladiss** [comment]
When receiving an MDF file from a different group, I would open it with the HDF Viewer first most probably. Then, /_myVar would be much nicer to read than /UDmyVar.
Therefore, I would favor the "_" solution, /detail-group could be fine as well but not as catchy because I would need to open an additional group in the HDF Viewer 😄

**Comment by MandyA** [comment]
I vote for the _myVar version as well.
Actually, I don't see any issues with C++. The IMT framework has its own variable structure independent of the data format. 

@NeumannIMT: I strongly recommend that your personal code fits to the IMT code rather than the MDF specification.

**Comment by tknopp** [comment]
I don't support #91 since it reads like that we cannot decide what we want. We are again putting extremely much effort into something that is absolutely irrelevant. If somebody wants to store data into `/mygroup/detail` than simply do it. The MDF will certainly not use that name. 

I will close this since the majority has no problem with `_` and since we do not actively disallow `/mygroup/detail` so that Alexander can use that (whatever framework he uses)
